create table public.department
(
    id       bigint generated by default as identity
        primary key,
    name     varchar(255),
    programs json
);

create table public.plan
(
    id         bigint generated by default as identity
        primary key,
    created_at date,
    status     varchar(255),
    student_id bigint,
    topic_id   bigint
);

create table public.plan_week
(
    id          bigint generated by default as identity
        primary key,
    plan_id     bigint,
    result      varchar(255),
    task        varchar(255),
    week_number integer
);

create table public.student
(
    id              bigint generated by default as identity
        primary key,
    dep_id          bigint,
    firstname       varchar(255),
    is_choosed      boolean,
    lastname        varchar(255),
    mail            varchar(255),
    program         varchar(255),
    proposed_number integer,
    sisi_id         varchar(255)
);

create table public.teacher
(
    id                  bigint generated by default as identity
        primary key,
    dep_id              bigint,
    firstname           varchar(255),
    lastname            varchar(255),
    mail                varchar(255),
    num_of_choosed_stud integer
);

create table public.topic
(
    id              bigint generated by default as identity
        primary key,
    created_at      date,
    created_by_id   bigint,
    created_by_type varchar(255),
    fields          json,
    form_id         bigint,
    program         varchar(255),
    status          varchar(255)
);

create table public.topic_request
(
    id                bigint generated by default as identity
        primary key,
    is_selected       boolean,
    req_note          varchar(255),
    req_text          varchar(255),
    requested_by_id   bigint,
    requested_by_type varchar(255),
    selected_at       date,
    topic_id          bigint
);

create table public.plan_response
(
    id            bigint generated by default as identity
        primary key,
    approver_id   bigint,
    approver_type varchar(255),
    note          varchar(255),
    plan_id       bigint,
    res           varchar(255),
    res_date      date
);

create index if not exists idx_student_dep_id on public.student(dep_id);
create index if not exists idx_teacher_dep_id on public.teacher(dep_id);
create index if not exists idx_topic_status on public.topic(status);
create index if not exists idx_topic_program on public.topic(program);
create index if not exists idx_topic_request_topic_id on public.topic_request(topic_id);
create index if not exists idx_plan_student_id on public.plan(student_id);
create index if not exists idx_plan_topic_id on public.plan(topic_id);
create index if not exists idx_plan_week_plan_id on public.plan_week(plan_id);
create index if not exists idx_plan_response_plan_id on public.plan_response(plan_id);
